changelog:
  exclude:
    labels:
      - ignore-for-release
  categories:
    - title: Breaking Changes
      labels:
        - breaking-change
    - title: Enhancements
      labels:
        - enhancement
    - title: Bug Fixes
      labels:
        - bug-fix
    - title: Documentation
      labels:
        - documentation
    - title: Other Changes
      labels:
        - "*"
