[project]
name = "uv-runner"
version = "0.1.0"
description = "Run scripts defined in uv-managed pyproject.toml files."
authors = [
    { name = "Brandon Carpenter", email = "brandon@avantus.com" }
]
dependencies = [
    "click ~= 8.1.7",
    "tomli ~= 2.0.1; python_version < '3.11'",
]
readme = "README.md"
requires-python = ">= 3.10"
license.file = "LICENSE.txt"
classifiers = [
    "Development Status :: 4 - Beta",
    "Environment :: Console",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: BSD License",
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Topic :: Software Development :: Build Tools",
    "Typing :: Typed",
]

[project.scripts]
"rr" = "uv_runner.__main__:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.uv]
dev-dependencies = [
    "mypy ~= 1.11.1",
]

[tool.hatch.build.targets.sdist]
only-include = [
    '.python-version',
    'uv.lock',
    'src/uv_runner/',
    '.gitignore',
    'LICENSE.txt',
    'README.md',
    'pyproject.toml',
]

[tool.hatch.build.targets.wheel]
packages = ["src/uv_runner"]

[tool.mypy]
mypy_path = "src"
packages = "uv_runner"
strict = true
