[project]
name = "rye-runner"
version = "0.1.0"
description = "Run tasks/scripts defined in pyproject.toml files using rye"
authors = [
    { name = "Brandon Carpenter", email = "brandon@avantus.com" }
]
dependencies = [
    "click ~= 8.1.7",
]
readme = "README.md"
requires-python = ">= 3.10"
license = { text = "BSD-3-Clause" }
classifiers = [
    "Development Status :: 4 - Beta",
    "Environment :: Console",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: BSD License",
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Topic :: Software Development :: Build Tools",
    "Typing :: Typed",
]

[project.scripts]
"rr" = "rye_runner:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.rye]
managed = true
dev-dependencies = [
    "mypy ~= 1.11.1",
]

[tool.hatch.metadata]
allow-direct-references = true

[tool.hatch.build.targets.wheel]
packages = ["src/rye_runner"]

[tool.mypy]
strict = true
